version: '3'
services:
  trading-app-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DB: trading_data
      BINANCE_SYMBOLS: btcusdt,ethusdt,pepeusdt
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: trading_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
